package com.example.peter.thekitchenmenu.data.entity;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.database.Exclude;

import java.util.HashMap;
import java.util.Map;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import static com.example.peter.thekitchenmenu.data.entity.DmProdComm.TABLE_PRODUCT_COMM;

/**
 * A community product model that holds product fields common to all users.
 */
@Entity(tableName = TABLE_PRODUCT_COMM)
public class DmProdComm implements Parcelable {

    public static final String TAG = "DmProdComm";

    /*
     * Table community_product - Stores information that is generic to the product. Note: These
     * constants match the field names in the remote database where possible.
     */
    public static final String TABLE_PROD_COMM_ID = "id";
    public static final String TABLE_PRODUCT_COMM = "product_community";
    public static final String TABLE_PROD_COMM_DESC = "description";
    public static final String TABLE_PROD_COMM_MADE_BY = "madeBy";
    public static final String TABLE_PROD_COMM_CATEGORY = "category";
    public static final String TABLE_PROD_COMM_SHELF_LIFE = "shelfLife";
    public static final String TABLE_PROD_COMM_PACK_SIZE = "packSize";
    public static final String TABLE_PROD_COMM_UNIT_OF_MEASURE = "unitOfMeasure";
    public static final String TABLE_PROD_COMM_PRICE_AVE = "packAvePrice";
    public static final String TABLE_PROD_COMM_CREATED_BY = "createdBy";
    public static final String TABLE_PROD_COMM_REMOTE_IMAGE_URI = "fbStorageImageUri";
    public static final String TABLE_PROD_COMM_CREATE_DATE = "comm_create_date";
    public static final String TABLE_PROD_COMM_LAST_UPDATE = "comm_last_updated";
    public static final String TABLE_PROD_COMM_REMOTE_REF_ID = "fbProductReferenceKey";

    @Exclude // Excludes field from Firebase, as is only required for Room.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = TABLE_PROD_COMM_ID)
    private int id;

    // Community product information.
    @ColumnInfo(name = TABLE_PROD_COMM_DESC)
    private String mDescription;

    @ColumnInfo(name = TABLE_PROD_COMM_MADE_BY)
    private String mMadeBy;

    @ColumnInfo(name = TABLE_PROD_COMM_CATEGORY)
    private int mCategory;

    @ColumnInfo(name = TABLE_PROD_COMM_SHELF_LIFE)
    private int mShelfLife;

    @ColumnInfo(name = TABLE_PROD_COMM_PACK_SIZE)
    private int mPackSize;

    @ColumnInfo(name = TABLE_PROD_COMM_UNIT_OF_MEASURE)
    private int mUnitOfMeasure;

    @ColumnInfo(name = TABLE_PROD_COMM_PRICE_AVE)
    private double mPackAvePrice;

    @ColumnInfo(name = TABLE_PROD_COMM_CREATED_BY)
    private String mCreatedBy;

    @ColumnInfo(name = TABLE_PROD_COMM_REMOTE_IMAGE_URI)
    @NonNull
    private String mFbStorageImageUri = "";

    @ColumnInfo(name = TABLE_PROD_COMM_CREATE_DATE)
    private long mCommCreateDate;

    @ColumnInfo(name = TABLE_PROD_COMM_LAST_UPDATE)
    private long mCommLastUpdate;

    @ColumnInfo(name = TABLE_PROD_COMM_REMOTE_REF_ID)
    private String mFbProductReferenceKey;

    /* Empty constructor as required by Firebase. */
    @Ignore
    public DmProdComm(){}

    /**
     * Constructor for Room
     * @param id A unique ID, auto generated by Room.
     * @param description A string describing the product.
     * @param madeBy A string describing the name of the maker of the product.
     * @param category An integer between 0 and 3 - see strings.xml for a definition.
     * @param shelfLife An integer between 1 and 16 - see strings.xml for a definition.
     * @param mPackSize An integer describing the weight or volume of the product.
     * @param unitOfMeasure An integer between 0 and 3 - see strings.xml for a definition.
     * @param packAvePrice A double automatically calculated by a Firebase function.
     * @param createdBy The user ID of the user that created this product.
     * @param fbStorageImageUri A String containing a Firestore URL set to an image of the product.
     * @param commCreateDate A long TIMESTAMP describing when the product was first created.
     * @param commLastUpdate A long TIMESTAMP describing when the product was last updated.
     */
    public DmProdComm(int id,
                      String description,
                      String madeBy,
                      int category,
                      int shelfLife,
                      int mPackSize,
                      int unitOfMeasure,
                      double packAvePrice,
                      String createdBy,
                      @NonNull String fbStorageImageUri,
                      long commCreateDate,
                      long commLastUpdate,
                      String fbProductReferenceKey) {

        this.id = id;
        this.mDescription = description;
        this.mMadeBy = madeBy;
        this.mCategory = category;
        this.mShelfLife = shelfLife;
        this.mPackSize = mPackSize;
        this.mUnitOfMeasure = unitOfMeasure;
        this.mPackAvePrice = packAvePrice;
        this.mCreatedBy = createdBy;
        this.mFbStorageImageUri = fbStorageImageUri;
        this.mCommCreateDate = commCreateDate;
        this.mCommLastUpdate = commLastUpdate;
        this.mFbProductReferenceKey = fbProductReferenceKey;
    }


    @Ignore
    public DmProdComm(Parcel in) {
        id = in.readInt();
        mDescription = in.readString();
        mMadeBy = in.readString();
        mCategory = in.readInt();
        mShelfLife = in.readInt();
        mPackSize = in.readInt();
        mUnitOfMeasure = in.readInt();
        mPackAvePrice = in.readDouble();
        mCreatedBy = in.readString();
        mFbStorageImageUri = in.readString();
        mCommCreateDate = in.readLong();
        mCommLastUpdate = in.readLong();
        mFbProductReferenceKey = in.readString();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(id);
        dest.writeString(mDescription);
        dest.writeString(mMadeBy);
        dest.writeInt(mCategory);
        dest.writeInt(mShelfLife);
        dest.writeInt(mPackSize);
        dest.writeInt(mUnitOfMeasure);
        dest.writeDouble(mPackAvePrice);
        dest.writeString(mCreatedBy);
        dest.writeString(mFbStorageImageUri);
        dest.writeLong(mCommCreateDate);
        dest.writeLong(mCommLastUpdate);
        dest.writeString(mFbProductReferenceKey);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<DmProdComm> CREATOR = new Creator<DmProdComm>() {
        @Override
        public DmProdComm createFromParcel(Parcel in) {
            return new DmProdComm(in);
        }

        @Override
        public DmProdComm[] newArray(int size) {
            return new DmProdComm[size];
        }
    };

    @Exclude // HashMap for FireBase community product information Map
    public Map<String, Object> commProductToMap() {

        HashMap<String, Object> result = new HashMap<>();

        result.put(TABLE_PROD_COMM_DESC, mDescription);
        result.put(TABLE_PROD_COMM_MADE_BY, mMadeBy);
        result.put(TABLE_PROD_COMM_CATEGORY, mCategory);
        result.put(TABLE_PROD_COMM_SHELF_LIFE, mShelfLife);
        result.put(TABLE_PROD_COMM_PACK_SIZE, mPackSize);
        result.put(TABLE_PROD_COMM_UNIT_OF_MEASURE, mUnitOfMeasure);
        result.put(TABLE_PROD_COMM_PRICE_AVE, mPackAvePrice);
        result.put(TABLE_PROD_COMM_CREATED_BY, mCreatedBy);
        result.put(TABLE_PROD_COMM_REMOTE_IMAGE_URI, mFbStorageImageUri);
        result.put(TABLE_PROD_COMM_CREATE_DATE, mCommCreateDate);
        result.put(TABLE_PROD_COMM_LAST_UPDATE, mCommLastUpdate);

        return result;
    }

    @Override
    public String toString() {
        return "Product ID: " + this.id + "\n" +
                "Description: " + mDescription + "\n" +
                "Made by: " + mMadeBy + "\n" +
                "Category: " + mCategory + "\n" +
                "Shelf life: " + mShelfLife + "\n" +
                "Pack size: " + mPackSize + "\n" +
                "Unit of measure: " + mUnitOfMeasure + "\n" +
                "Pack price ave: " + mPackAvePrice + "\n" +
                "Created by: " + mCreatedBy + "\n" +
                "Firebase image URI: " + mFbStorageImageUri + "\n" +
                "Create date: " + mCommCreateDate + "\n" +
                "Last update: " + mCommLastUpdate + "\n" +
                "Product ref key: " + mFbProductReferenceKey;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescription() {
        return mDescription;
    }

    public void setDescription(String description) {
        this.mDescription = description;
    }

    public String getMadeBy() {
        return mMadeBy;
    }

    public void setMadeBy(String madeBy) {
        this.mMadeBy = madeBy;
    }

    public int getCategory() {
        return mCategory;
    }

    public void setCategory(int category) {
        this.mCategory = category;
    }

    public int getShelfLife() {
        return mShelfLife;
    }

    public void setShelfLife(int shelfLife) {
        this.mShelfLife = shelfLife;
    }

    public int getPackSize() {
        return mPackSize;
    }

    public void setPackSize(int packSize) {
        this.mPackSize = packSize;
    }

    public int getUnitOfMeasure() {
        return mUnitOfMeasure;
    }

    public void setUnitOfMeasure(int unitOfMeasure) {
        this.mUnitOfMeasure = unitOfMeasure;
    }

    public double getPackAvePrice() {
        return mPackAvePrice;
    }

    public void setPackAvePrice(double packAvePrice) {
        this.mPackAvePrice = packAvePrice;
    }

    public String getCreatedBy() {
        return mCreatedBy;
    }

    public void setCreatedBy(String createdBy) {
        this.mCreatedBy = createdBy;
    }

    @NonNull
    public String getFbStorageImageUri() {
        return mFbStorageImageUri;
    }

    public void setFbStorageImageUri(@NonNull String fbStorageImageUri) {
        this.mFbStorageImageUri = fbStorageImageUri;
    }

    public long getCommCreateDate() {
        return mCommCreateDate;
    }

    public void setCommCreateDate(long commCreateDate) {
        this.mCommCreateDate = commCreateDate;
    }

    public long getCommLastUpdate() {
        return mCommLastUpdate;
    }

    public void setCommLastUpdate(long commLastUpdate) {
        this.mCommLastUpdate = commLastUpdate;
    }

    public String getFbProductReferenceKey() {
        return mFbProductReferenceKey;
    }

    public void setRemoteProdRefKey(String fbProductReferenceKey) {
        this.mFbProductReferenceKey = fbProductReferenceKey;
    }
}
